// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7Le2ApHkqpv6qLZ2kOCsJzLcZoZd7_A',
    appId: '1:841010737348:web:aa1fd4ce6cbe8de2961991',
    messagingSenderId: '841010737348',
    projectId: 'child-tracker-c23fd',
    authDomain: 'child-tracker-c23fd.firebaseapp.com',
    storageBucket: 'child-tracker-c23fd.appspot.com',
    measurementId: 'G-0Z2G5TZVET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZT8PMNoR2Qdb98briMr7PotwnqscqM8',
    appId: '1:841010737348:android:ca9741864b17d833961991',
    messagingSenderId: '841010737348',
    projectId: 'child-tracker-c23fd',
    storageBucket: 'child-tracker-c23fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6O0xMAFby68HYtnchnmI70h9xkdIO2Dc',
    appId: '1:841010737348:ios:74fa2f030bafb069961991',
    messagingSenderId: '841010737348',
    projectId: 'child-tracker-c23fd',
    storageBucket: 'child-tracker-c23fd.appspot.com',
    iosBundleId: 'com.example.locationApp',
  );
}
